pipelines:
  - name: docker_build_pipeline
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup:docker_afgroup             # Execute build and push on the same node
          dockerFileLocation: .
          dockerFileName:Dockerfile
          dockerImageName:'pipe-master.jfrog.info:8081/docker-local/alpine37'
          dockerImageTag:7
          inputResources:
            - name: repo_docker_build_push
          integrations:
            - name: artifactory

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: docker_afgroup             # Execute build and push on the same node
          targetRepository: docker-local
          integrations:
            - name: artifactory
          inputSteps:
            - name: docker_build

      - name: publish_build_info
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: build_info_docker_build_push
